# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: joshuacender.com
email: hello@joshuacender.com
description: > # this means to ignore newlines until "baseurl:"
  Code me a sandwich.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshuacender.com" # the base hostname & protocol for your site
github_username:  sixthgear
linkedin_username: joshua-cender-58238113

# Build settings
markdown: kramdown
