# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: joshuacender.com
email: hello@joshuacender.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Joshua Cender and I’m an experienced entrepreneur and engineer from Vancouver, British Columbia.
  My two favorite topics are business and software; I’m always looking for new opportunities to connect them!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshuacender.com" # the base hostname & protocol for your site
github_username:  sixthgear
linkedin_username: joshua-cender-58238113
google_analytics: UA-78892820-1

# Build settings
markdown: kramdown
